rvm:           # перечень всех версий Ruby, на которых хотите протестировать
  - 1.9.2

before_script:
 - "rake db:migrate"
 - "rails server -d -e test"

script: "bundle exec rake test" # команда для запуска тестов

after_script
- "kill -9 `cat tmp/pids/server.pid`"  
